#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Figlut.MonoDroid.DataBox.Resource", IsApplication=true)]

namespace Figlut.MonoDroid.DataBox
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Figlut.MonoDroid.DataBox.Configuration.Resource.String.library_name = global::Figlut.MonoDroid.DataBox.Resource.String.library_name;
			global::Figlut.MonoDroid.DataBox.Utilities.Resource.String.library_name = global::Figlut.MonoDroid.DataBox.Resource.String.library_name;
			global::Figlut.MonoDroid.Toolkit.Resource.String.library_name = global::Figlut.MonoDroid.DataBox.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int figlut_configuration_manager = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int figlut_data_box_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int figlut_database = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int figlut_exit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int figlut_help = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int figlut_logging = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int figlut_logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int figlut_manager = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int figlut_mobile_databox = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int figlut_service = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int figlut_web_service = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int figlut_web_site = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int file = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int folder = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int ConfigManagerRow = 2131034123;
			
			// aapt resource value: 0x7f050021
			public const int EditSettingsRow = 2131034145;
			
			// aapt resource value: 0x7f050000
			public const int border_bottom = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int border_left = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int border_right = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int config_manager_content = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int content = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int content_stub = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int data_box_content = 2131034127;
			
			// aapt resource value: 0x7f050019
			public const int data_box_row = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int edit_settings_content = 2131034140;
			
			// aapt resource value: 0x7f050035
			public const int edit_text_password = 2131034165;
			
			// aapt resource value: 0x7f050033
			public const int edit_text_user_name = 2131034163;
			
			// aapt resource value: 0x7f050023
			public const int file_picker_activity_content = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int file_picker_row = 2131034149;
			
			// aapt resource value: 0x7f050011
			public const int header_layout = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int image_category = 2131034124;
			
			// aapt resource value: 0x7f050026
			public const int image_file_list_item = 2131034150;
			
			// aapt resource value: 0x7f05003a
			public const int image_item = 2131034170;
			
			// aapt resource value: 0x7f050004
			public const int image_logo = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int layout_content = 2131034115;
			
			// aapt resource value: 0x7f05003d
			public const int layout_manage_entity_input_controls = 2131034173;
			
			// aapt resource value: 0x7f050009
			public const int list_config_manager = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int list_data_box = 2131034132;
			
			// aapt resource value: 0x7f050020
			public const int list_edit_settings = 2131034144;
			
			// aapt resource value: 0x7f050024
			public const int list_file_picker = 2131034148;
			
			// aapt resource value: 0x7f050038
			public const int list_main_menu = 2131034168;
			
			// aapt resource value: 0x7f05002a
			public const int list_select_data_box = 2131034154;
			
			// aapt resource value: 0x7f050028
			public const int load_data_box_content = 2131034152;
			
			// aapt resource value: 0x7f05002b
			public const int log_viewer_content = 2131034155;
			
			// aapt resource value: 0x7f050030
			public const int main_activity_content = 2131034160;
			
			// aapt resource value: 0x7f050039
			public const int main_menu_row = 2131034169;
			
			// aapt resource value: 0x7f050016
			public const int menu_item_add = 2131034134;
			
			// aapt resource value: 0x7f05003e
			public const int menu_item_apply = 2131034174;
			
			// aapt resource value: 0x7f05002f
			public const int menu_item_clear = 2131034159;
			
			// aapt resource value: 0x7f050015
			public const int menu_item_delete = 2131034133;
			
			// aapt resource value: 0x7f050036
			public const int menu_item_login = 2131034166;
			
			// aapt resource value: 0x7f050017
			public const int menu_item_refresh = 2131034135;
			
			// aapt resource value: 0x7f05000a
			public const int menu_item_reset_all_settings = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int menu_item_save = 2131034136;
			
			// aapt resource value: 0x7f05002d
			public const int scroll_log_viewer = 2131034157;
			
			// aapt resource value: 0x7f05000d
			public const int text_category = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int text_category_description = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int text_configuration_manager_title = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int text_data_box_title = 2131034128;
			
			// aapt resource value: 0x7f050029
			public const int text_data_boxes = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int text_file_list_item = 2131034151;
			
			// aapt resource value: 0x7f05003b
			public const int text_item_name = 2131034171;
			
			// aapt resource value: 0x7f05002e
			public const int text_log_viewer = 2131034158;
			
			// aapt resource value: 0x7f05002c
			public const int text_log_viewer_title = 2131034156;
			
			// aapt resource value: 0x7f050031
			public const int text_login_title = 2131034161;
			
			// aapt resource value: 0x7f050037
			public const int text_main_title = 2131034167;
			
			// aapt resource value: 0x7f05003c
			public const int text_manage_entity_title = 2131034172;
			
			// aapt resource value: 0x7f050034
			public const int text_password = 2131034164;
			
			// aapt resource value: 0x7f05001a
			public const int text_primary_value = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int text_primary_value_header = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int text_secondary_value = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int text_secondary_value_header = 2131034131;
			
			// aapt resource value: 0x7f050022
			public const int text_setting_display_name = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int text_setting_name = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int text_setting_value = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int text_settings_category_title = 2131034141;
			
			// aapt resource value: 0x7f050032
			public const int text_user_name = 2131034162;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int base_activity_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int config_manager_activity_content_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int config_manager_main_menu_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int config_manager_row_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int data_box_activity_content_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int data_box_context_menu_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int data_box_main_menu_layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int data_box_row_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int edit_settings_acitivity_content_layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int edit_settings_row_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int file_picker_content_layout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int file_picker_row_layout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int load_data_box_activity_content_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int log_viewer_activity_content_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int log_viewer_activity_main_menu_layout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int login_activity_content_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int login_activity_main_menu_layout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int main_activity_content_layout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int main_menu_row_layout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int manage_entity_content_layout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int manage_entity_main_menu_layout = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040015
			public const int add = 2130968597;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040014
			public const int apply = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int cancel = 2130968595;
			
			// aapt resource value: 0x7f04001c
			public const int clear = 2130968604;
			
			// aapt resource value: 0x7f040003
			public const int configuration_manager = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int data_box = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int data_box_settings_description = 2130968585;
			
			// aapt resource value: 0x7f040010
			public const int data_boxes = 2130968592;
			
			// aapt resource value: 0x7f040016
			public const int delete = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int exit = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int log_viewer = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int logging = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int logging_settings_description = 2130968587;
			
			// aapt resource value: 0x7f04001f
			public const int login = 2130968607;
			
			// aapt resource value: 0x7f040011
			public const int manage_entity = 2130968593;
			
			// aapt resource value: 0x7f040004
			public const int mobile_data_box = 2130968580;
			
			// aapt resource value: 0x7f04001e
			public const int password = 2130968606;
			
			// aapt resource value: 0x7f04000e
			public const int primary_column = 2130968590;
			
			// aapt resource value: 0x7f040017
			public const int refresh = 2130968599;
			
			// aapt resource value: 0x7f040005
			public const int reinitialize = 2130968581;
			
			// aapt resource value: 0x7f04001b
			public const int reset_settings = 2130968603;
			
			// aapt resource value: 0x7f040018
			public const int save = 2130968600;
			
			// aapt resource value: 0x7f04000f
			public const int secondary_column = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int set = 2130968594;
			
			// aapt resource value: 0x7f040019
			public const int setting_name = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int setting_value = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public const int user_name = 2130968605;
			
			// aapt resource value: 0x7f040006
			public const int web_service = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int web_service_settings_description = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
